### ISSUE TITLE
Add analysis report

### ISSUE THREAD

**Issue by tomstafford** [annakrystalli/xspl_power_analyser#11]
At the bottom add a report of the test, and/or a button to generate this
e.g
"Test type: between subjects test
Power = 0.8
Effect size = 0.3
Total required sample = 160 (80 in each group)
For details on the calculation see [[link]]

**Comment by annakrystalli** [comment]
A nice idea but not sure we've got time to implement for this release. Is that cool?

**Comment by tomstafford** [comment]
Yes, let's leave this
