### ISSUE TITLE
clarify plot

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/xspl_power_analyser#12]
Here's a prelim plot for power ~ n for a given subset of effect sizes:

![image](https://user-images.githubusercontent.com/5583057/35994898-b280e4b0-0d09-11e8-9398-e7add813ee16.png)

There is little overlap in the effect size x power testing conditions for accuracy, drift and rt atm. I imagine this will be addressed in the full dataset? 

Also, I imagine a smooth is a good trendline approach for the simulation?

**Comment by tomstafford** [comment]
This doesn't look right - my plots of the same data have "drift" rising faster in power with n than "reaction time" (and there is also a "accuracy" curve) too. See attached

![hitrate](https://user-images.githubusercontent.com/1650616/36031391-83690862-0da2-11e8-8c89-5d2f56e8a3db.png)

The summary.csv file provides point estimates, so there isn't the information to calculate confidence intervals. I agree smoothing would work

**Comment by annakrystalli** [comment]
So the data plotted has been subsetted for a particular effect size window (2-6) which is why it's not all there. There's currently no determination of accuracy with effect sizes greater than 0 (they are pretty much all negative: 
![image](https://user-images.githubusercontent.com/5583057/36034063-b1afe3dc-0daa-11e8-8b9c-9f927c506610.png)

**Comment by annakrystalli** [comment]
Here's an attempt at the plot with another effect size window (`filter(effect size > -0.9 & effect size < 1)`) so that it captures all three tested conditions: 
![image](https://user-images.githubusercontent.com/5583057/36034108-e2ac6ae6-0daa-11e8-807f-568f01eecbdf.png). Clearly the effect size window is too broad and numerous effect size test conditions being included. The key for the final app will be to sensibly bin the data to both separate the conditions adequately and hopefully allow a simple specification of the sliders (although I can hack into them if need be).

**Comment by annakrystalli** [comment]
I think we should include an overall contour plot of the 3D data (ie n as x and toggle power and effect size as y and z. Will knock a demo up.

**Comment by tomstafford** [comment]
For development we need to not bin effect sizes. I have sparsely sampled the space, so it does not make any sense to bin them (or, alternatively, it only makes sense to bin over a narrow window such as +/- 0.01). The graph should be point estimates. 

Since point estimates are generated from a larger underlying data set, I can provide uncertainty estimates directly in whatever format/metric you'd like - they should not be calculated over the point estimates in the summary file

**Comment by tomstafford** [comment]
Contour plot - sure, that would be neat!

**Comment by tomstafford** [comment]
Additionally

You should only index by "Drift effect size". Ignore the others (Acc effect size and RT effect size).

The plot for effect size of zero is important

**Comment by annakrystalli** [comment]
![image](https://user-images.githubusercontent.com/5583057/36145247-b1a85a9e-10a8-11e8-9423-f4ab92ccee8d.png)

**Comment by annakrystalli** [comment]
Clearly the data is quite sparse atm but think it will look cool in the app. We could link the two plots together. :)

**Comment by tomstafford** [comment]
Yes, that's lovely - and will look even better when I generate less sparse data
