### ISSUE TITLE
Publication strategy

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/xspl_power_analyser#14]
## Options

There are three research outputs involved:
1) The paper
2) The data
3) The shinyapp

I have looked online for advice but what I have found has just confirmed the options available rather that help me decide which one to go for. (eg https://community.rstudio.com/t/can-i-publish-a-shiny-app-in-a-scientific-journal-how-where/6306/5)The possible options I can see are:

1) Publish everything as one DOI.
2) Publish the paper & app under one DOI and the data in ORDA.
3) Publish all 3 under separate DOIs (the app and dataset in ORDA). However, this seems like a duplication as it would result in data being published as part of both the app and on it’s own although once the data is published I could probably set the app up to source the data from ORDA)
4) Publish the paper separately and the app and data as one DOI but tweak the app to allow for downloading the data through it.

**Comment by annakrystalli** [comment]
## Strategy Decision

- Code & Data are already published in [ddm_sims](https://github.com/tomstafford/ddm_sims) repository and already have a [Zenodo DOI](https://zenodo.org/record/2648995)
- To archive app, we'll submit to ORDA when finalised (see issue #15).

**Comment by annakrystalli** [comment]
Reserved **DOI 10.15131/shef.data.8109161** (not published yet) at https://figshare.shef.ac.uk/s/11f65856db28308644a4

**Comment by annakrystalli** [comment]
Regarding the Categories and keywords I've added to the ORDA entry, happy with those @tomstafford ?

**Comment by tomstafford** [comment]
How do I see these please?

**Comment by annakrystalli** [comment]
If you click on the link above 👆, the categories and keywords should be on the right-hand panel.

**Comment by annakrystalli** [comment]
Here it is again: Reserved DOI 10.15131/shef.data.8109161 (not published yet) at https://figshare.shef.ac.uk/s/11f65856db28308644a4

**Comment by tomstafford** [comment]
I see it now, apologies

Let's change "power analyses" to "power analysis" since that is more common

And add "drift diffusion model", "speed-accuracy trade-off", "reaction times" as keywords please
