### ISSUE TITLE
viz range of deviation from estimated effect 

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/xspl_power_analyser#4]
Be able to see the range of estimated effects that would be considered significant under current experiment design settings.

**Comment by tomstafford** [comment]
I think range isn't quite right here - power analysis identifies a *minimum* effect which can be detected by a design, so the range is "everything above X"

**Comment by tomstafford** [comment]
related: we should discuss the upper and lower estimate lines that are currently shown. I didn't understand how these are calculated and am not sure the are needed
