### ISSUE TITLE
Make x-axis total number of subjects

### ISSUE THREAD

**Issue by tomstafford** [annakrystalli/xspl_power_analyser#9]
Currently x-axis is number of subjects in each group, but it would be consistent across designs to show total number of subjects, as well as emphasising the benefits of a within subjects design (because switching to a between subjects design immediately doubles your participant requirements)

**Comment by annakrystalli** [comment]
Is what we've got at the minute correct? Or does this still need addressing?

**Comment by tomstafford** [comment]
this has made me realise a couple of inconsistencies in the labelling of the axes. I will try and correct and issue a PR (if that's the right thing)

**Comment by tomstafford** [comment]
I have made a PR for a change to the bottom row (the report of participant numbers)

I cannot change the top row so it is more precise. Currently, when "true effect size" is selected in the "select x axis variable" option, the slide header reads "Select sample size". This should read "Select sample size per group", but I can't do this without making the app crash!

**Comment by annakrystalli** [comment]
OK @tomstafford I've sorted this now!

It does however make me wonder whether the x-axis label in the plot for effect size should be _effect size in drift_  as each line indicates the minimum detectable effect size for each variable at a given group sample size.

**Comment by tomstafford** [comment]
No, this is correct as it is (the explanation is quite involved - it is in the paper!)

**Comment by annakrystalli** [comment]
Oh yeah, I remember you explaining it now. 👍
